[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
oft = "2mhvauHMDZvoZktkS5vBDVheNRwiW9fWAPTYLSF98k43"

[programs.devnet]
oft = "2mhvauHMDZvoZktkS5vBDVheNRwiW9fWAPTYLSF98k43"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./junk-id.json"

[scripts]
test = "npx jest test/anchor"
